### PR TITLE
ClickGUI.

### PR DESCRIPTION
**Pull request by Officer32k**
gui i wrote for u zihasz!1!1!1

### CODE REVIEW

**Comment by MOMIN5** [comment]
7:30 am lol

**Comment by MOMIN5** [comment]
@zihasz also remove .idea folder

**Comment by Officer32k** [comment]
> 7:30 am lol

yes yes ...also i wrote this while i had drank half a bottle of 40% whiskey meaning everything i wrote here is plain china

**Comment by Officer32k** [comment]
idk what half the shit i wrote does i just wrote off of memory and by some fucking miracle it works

**Comment by MOMIN5** [comment]
based

**Comment by Officer32k** [comment]
@zihasz  why did u remove it?

**Comment by zihasz** [comment]
because

**Pull request merged**
